pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Scar2603/JenkinsPipeline.git', branch: 'main'
            }
        }
        
        stage('Build') {
            steps {
                dir('helloworld') { 
                    bat 'mvn clean package'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('helloworld') { 
                    bat 'mvn test'
                }
            }
        }
        
        stage('Run') {
            steps {
                dir('helloworld') {
                    bat 'mvn exec:java -Dexec.mainClass="com.example.App"' 
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'helloworld/target/*.jar', fingerprint: true 
            
            cleanWs()
        }
    }
}
